/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package megabasterd;

import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import static megabasterd.MainPanel.FONT_DEFAULT;
import static megabasterd.MainPanel.THREAD_POOL;
import static megabasterd.MiscTools.Bin2BASE64;
import static megabasterd.MiscTools.HashBin;
import static megabasterd.MiscTools.swingReflectionInvoke;
import static megabasterd.MiscTools.updateFont;


/**
 *
 * @author tonikelope
 */
public class GetMegaMasterPasswordDialog extends javax.swing.JDialog {

    private boolean _pass_ok;
    
    private String _current_pass_hash;
    
    private final String _salt;
    
    private byte[] _pass;

    public JPasswordField getNew_pass_textfield() {
        return current_pass_textfield;
    }

    public JCheckBox getRemember_checkbox() {
        return remember_checkbox;
    }

    public boolean isPass_ok() {
        return _pass_ok;
    }

    public byte[] getPass() {
        return _pass;
    }
    
    public void deletePass() {
        
        for(byte c:_pass) {
            
            c = 0;
        }
        
        _pass = null;
    }

    /**
     * Creates new form MegaPassDialog
     */
    public GetMegaMasterPasswordDialog(java.awt.Frame parent, boolean modal, String current_pass_hash, String salt) {
        super(parent, modal);
        initComponents();
        
        updateFont(ok_button, FONT_DEFAULT, Font.PLAIN);
        updateFont(cancel_button, FONT_DEFAULT, Font.PLAIN);
        updateFont(please_label, FONT_DEFAULT, Font.PLAIN);
        updateFont(status_label, FONT_DEFAULT, Font.PLAIN);
        updateFont(remember_checkbox, FONT_DEFAULT, Font.PLAIN);
        
        _current_pass_hash = current_pass_hash;

        _pass_ok = false;
        
        _pass = null;
        
        _salt = salt;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        current_pass_textfield = new javax.swing.JPasswordField();
        cancel_button = new javax.swing.JButton();
        ok_button = new javax.swing.JButton();
        lock_label = new javax.swing.JLabel();
        please_label = new javax.swing.JLabel();
        status_label = new javax.swing.JLabel();
        remember_checkbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MegaMasterPassword");
        setResizable(false);

        current_pass_textfield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        current_pass_textfield.setDoubleBuffered(true);
        current_pass_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                current_pass_textfieldKeyPressed(evt);
            }
        });

        cancel_button.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        cancel_button.setText("CANCEL");
        cancel_button.setDoubleBuffered(true);
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        ok_button.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        ok_button.setText("OK");
        ok_button.setDoubleBuffered(true);
        ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buttonActionPerformed(evt);
            }
        });

        lock_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/megabasterd/lock_medium.png"))); // NOI18N
        lock_label.setDoubleBuffered(true);

        please_label.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        please_label.setText("Please, enter your master password");
        please_label.setDoubleBuffered(true);

        status_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        status_label.setDoubleBuffered(true);

        remember_checkbox.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        remember_checkbox.setSelected(true);
        remember_checkbox.setText("Remember for this session");
        remember_checkbox.setDoubleBuffered(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(status_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ok_button)
                        .addGap(18, 18, 18)
                        .addComponent(cancel_button))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lock_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(please_label, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(current_pass_textfield)
                            .addComponent(remember_checkbox))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(please_label)
                        .addGap(18, 18, 18)
                        .addComponent(current_pass_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(remember_checkbox))
                    .addComponent(lock_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ok_button)
                        .addComponent(cancel_button))
                    .addComponent(status_label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        
        swingReflectionInvoke("setVisible", this, false);
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed
       
        swingReflectionInvoke("setText", status_label, "Verifying your password, please wait...");
        
        final GetMegaMasterPasswordDialog tthis = this;
        
        THREAD_POOL.execute(new Runnable(){
            
            @Override
            public void run() {try {
                byte[] pass = CryptTools.PBKDF2HMACSHA256(new String(current_pass_textfield.getPassword()), MiscTools.BASE642Bin(_salt), CryptTools.PBKDF2_ITERATIONS);

                String pass_hash = Bin2BASE64(HashBin("SHA-1", pass));

                if(!pass_hash.equals(_current_pass_hash)) {

                    JOptionPane.showMessageDialog(tthis, "BAD PASSWORD!", "Error", JOptionPane.ERROR_MESSAGE);
                    
                    swingReflectionInvoke("setText", status_label, "");

                } else {
                    
                    _pass = pass;
                    
                    _current_pass_hash = pass_hash;
                    
                    _pass_ok = true;
                
                    swingReflectionInvoke("setVisible", tthis, false);
                }

                for(byte b:pass) {

                    b = 0;
                }
 
        } catch (Exception ex) {
            Logger.getLogger(GetMegaMasterPasswordDialog.class.getName()).log(Level.SEVERE, null, ex);
        }}});
       
    }//GEN-LAST:event_ok_buttonActionPerformed

    private void current_pass_textfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_current_pass_textfieldKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            ok_buttonActionPerformed(null);
        }
    }//GEN-LAST:event_current_pass_textfieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JPasswordField current_pass_textfield;
    private javax.swing.JLabel lock_label;
    private javax.swing.JButton ok_button;
    private javax.swing.JLabel please_label;
    private javax.swing.JCheckBox remember_checkbox;
    private javax.swing.JLabel status_label;
    // End of variables declaration//GEN-END:variables
}
